In [1]:
import numpy as np

In [6]:
nums=[[1,2,3],[3,4,5]]
nums=np.array(nums)
print('nums: \n')
print(nums)
pums=[1,2,3]
pums=np.array(pums)
print('pums: \n')
print(pums)

nums: 

[[1 2 3]
 [3 4 5]]
pums: 

[1 2 3]


In [16]:
print(nums.shape) # 2D array or matrix
print(pums.shape) # 1D array or vectorS

(2, 3)
(3,)


In [20]:
print(nums.ndim)
print(pums.ndim)

2
1


In [21]:
print(nums.size)

6


In [22]:
#this will convert numpy array to list
nums.tolist()

[[1, 2, 3], [3, 4, 5]]

In [6]:
#Numpy Functions---> zeros ,eye, ones, diag, randint, rand,randn

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
arr=[[2., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 4., 0.]]
arr=np.array(arr)
np.diag(arr) # gives the diagonal element

array([2., 3., 4.])

In [70]:
random_arr=np.random.randint(1,15,4) #generates 4 random numbers between 1 and 14
random_arr

array([11, 11,  7, 14])

In [69]:
random_arr=np.random.rand(4) #generates 4 random numbers between 0 and 1 (1D array)
random_arr

array([0.98799529, 0.76599595, 0.77700444, 0.02798196])

In [27]:
random_arr=np.random.rand(2,3) #generates 2D array with elements values from 0 to 1
print(random_arr)
print(np.mean(random_arr))

[[0.44909227 0.22245619 0.76499598]
 [0.34136188 0.67942865 0.67095056]]
0.5213809231101799


In [8]:
random_arr=np.random.randn(4) #generates 4 numbers which are 0 centered
random_arr

array([ 0.1059318 , -1.99033708,  1.39742061,  2.53639818])

In [19]:
np.mean(random_arr)

0.017681669581408047

In [20]:
#Reshaping array

In [24]:
arr=np.random.randint(1,20,20)
arr

array([17, 15,  9,  5, 15, 13,  4, 15,  9,  6, 11,  8, 15,  2, 17, 14, 10,
       13, 12, 19])

In [25]:
arr.ndim
arr.shape

(20,)

In [26]:
arr=arr.reshape(2,10) #size 2*10= 20 equal to the size of the previous arr
#arr=arr.reshape(20)
arr

array([[17, 15,  9,  5, 15, 13,  4, 15,  9,  6],
       [11,  8, 15,  2, 17, 14, 10, 13, 12, 19]])

In [24]:
#-1 in reshape

In [25]:
arr=np.arange(1,11) #arange functions take inputs a and b and generates an 1D array of numbers ranging from a to b-1
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr.reshape(2,-1) # here numpy decides which number to fill the -1 place

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
arr.size #returns the size of the array

10

In [29]:
#seed functions

In [29]:
np.random.seed(123)
arr=np.random.randint(1,101,15)

In [31]:
arr.size

15

In [32]:
arr.shape

(15,)

In [33]:
arr.ndim

1

In [34]:
#indexing and slicing of 1D array

In [35]:
#indexing and slicing of 2D array

In [36]:
arr=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
#using double bracket notation calling single elements
print(arr[0][1])
print(arr[2][2])

10
45


In [38]:
#using single bracket notation calling single elements
print(arr[0,1])
print(arr[2,2])

10
45


In [39]:
#slicing using single bracket notation
arr
arr[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [40]:
#view vs copy

In [36]:
np.random.seed(123)
arr=np.random.randint(1,20,15)
sliced_arr=arr[2:10].copy().reshape(2,-1) #if copy() function is not given then the sliced_arr will act as a view of the main array arr
sliced_arr[:]=0
sliced_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
arr

array([14,  3,  3,  7, 18, 11,  2,  1, 18, 16, 10,  1, 15,  1, 16])

In [43]:
#conditional section

In [49]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
mask=arr>5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [58]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [53]:
l=[]
for i in arr:
    if i%2==0:
        l.append(i)
        
np.array(l)

array([ 2,  4,  6,  8, 10])

In [49]:
arr=np.random.rand(2,3)
arr[arr>.25]=0
arr

array([[0.        , 0.24475928, 0.        ],
       [0.        , 0.        , 0.        ]])

In [50]:
#operations scalar

In [68]:
np.random.seed(123)
arr=np.random.randint(1,10,15)
arr=arr.reshape(5,-1)
arr
arr+2
arr*2
arr**2

array([[ 9,  9, 49],
       [ 4, 16, 49],
       [ 4,  1,  4],
       [ 1,  1, 16],
       [25,  1,  1]], dtype=int32)

In [64]:
#operations involving two or more arrays

In [71]:
np.random.seed(123)
arr1=np.random.randint(1,15,15)
arr2=np.random.randint(1,15,15)
print(arr1)
print(arr2)

[14  3 13  3  7  2  4 11 12 10  7  2  1  2 10]
[ 1  1 10  4 14  5  1  1  5  2  8  4  3  5  8]


In [54]:
arr1+arr2
arr1*arr2
arr1**arr2
arr1/arr2

array([14.        ,  3.        ,  1.3       ,  0.75      ,  0.5       ,
        0.4       ,  4.        , 11.        ,  2.4       ,  5.        ,
        0.875     ,  0.5       ,  0.33333333,  0.4       ,  1.25      ])

In [55]:
#some useful functions

In [73]:
print('Array:');
print(arr)
print('Mean of the array',np.mean(arr));
print('Minimum of the array',np.min(arr));
print('Maximum of the array',np.max(arr));
print('Argmin',np.argmin(arr));  #gives the position of the minimum number
print('Argmax',np.argmax(arr));
print('Square Root',np.sqrt(arr));
print('Exponent',np.exp(arr));#euler number takes the matrix element to find exponent
print('Sin',np.sin(arr));
print('Cos',np.cos(arr));
print('Linspace',np.linspace(1,15,50)); #gives 50 numbers between 1 to 15 which are evenly spaced
print('Array: ',np.array([1,2,3,0],dtype='bool'));

Array:
[[3 3 7]
 [2 4 7]
 [2 1 2]
 [1 1 4]
 [5 1 1]]
Mean of the array 2.933333333333333
Minimum of the array 1
Maximum of the array 7
Argmin 7
Argmax 2
Square Root [[1.73205081 1.73205081 2.64575131]
 [1.41421356 2.         2.64575131]
 [1.41421356 1.         1.41421356]
 [1.         1.         2.        ]
 [2.23606798 1.         1.        ]]
Exponent [[  20.08553692   20.08553692 1096.63315843]
 [   7.3890561    54.59815003 1096.63315843]
 [   7.3890561     2.71828183    7.3890561 ]
 [   2.71828183    2.71828183   54.59815003]
 [ 148.4131591     2.71828183    2.71828183]]
Sin [[ 0.14112001  0.14112001  0.6569866 ]
 [ 0.90929743 -0.7568025   0.6569866 ]
 [ 0.90929743  0.84147098  0.90929743]
 [ 0.84147098  0.84147098 -0.7568025 ]
 [-0.95892427  0.84147098  0.84147098]]
Cos [[-0.9899925  -0.9899925   0.75390225]
 [-0.41614684 -0.65364362  0.75390225]
 [-0.41614684  0.54030231 -0.41614684]
 [ 0.54030231  0.54030231 -0.65364362]
 [ 0.28366219  0.54030231  0.54030231]]
Linspace [ 1.      

In [57]:
np.sum(arr)

75

In [58]:
np.max(arr)

9

In [18]:
test_array=np.linspace(1,15,20).reshape(4,5)
print(test_array)
print(test_array.max())
print(test_array.argmax())

[[ 1.          1.73684211  2.47368421  3.21052632  3.94736842]
 [ 4.68421053  5.42105263  6.15789474  6.89473684  7.63157895]
 [ 8.36842105  9.10526316  9.84210526 10.57894737 11.31578947]
 [12.05263158 12.78947368 13.52631579 14.26315789 15.        ]]
15.0
19


In [59]:
np.argmax(arr)

4

In [60]:
print(arr)
print(np.min(arr,axis=1))
print(np.min(arr,axis=0))

[[5 8 3]
 [5 9 1]
 [8 4 5]
 [7 2 6]
 [7 3 2]]
[3 1 4 2 2]
[5 2 1]


In [75]:
arr=arr.reshape(3,-1)
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.prod(arr,axis=0))

print(np.cumsum(arr,axis=1))

[[3 3 7 2 4]
 [7 2 1 2 1]
 [1 4 5 1 1]]
[11  9 13  5  6]
[19 13 12]
[21 24 35  4  4]
[[ 3  6 13 15 19]
 [ 7  9 10 12 13]
 [ 1  5 10 11 12]]


In [78]:
np.random.seed(123)
arr=np.random.randint(1,10,20)
print(arr)
print(np.random.shuffle(arr))
print(np.unique(arr))

[3 3 7 2 4 7 2 1 2 1 1 4 5 1 1 5 2 8 4 3]
None
[1 2 3 4 5 7 8]


In [79]:
print(arr)

np.unique(arr,return_index=True,return_counts=True)

[2 4 3 1 4 1 8 1 7 3 2 4 5 2 1 3 2 5 7 1]


(array([1, 2, 3, 4, 5, 7, 8]),
 array([ 3,  0,  2,  1, 12,  8,  6], dtype=int32),
 array([5, 4, 3, 3, 2, 2, 1]))

In [64]:
#horizontal and vertical stacking


In [65]:
np.random.seed(123)
arr=np.random.randint(1,20,15).reshape(3,5)
prr=np.random.randint(1,20,15).reshape(3,5)
print(np.hstack((arr,prr)))
print('\n')
print(np.vstack((arr,prr)))

[[14  3  3  7 18 15  5  1 17  5]
 [11  2  1 18 16 18  4  3  8  3]
 [10  1 15  1 16 16 17  8 10  4]]


[[14  3  3  7 18]
 [11  2  1 18 16]
 [10  1 15  1 16]
 [15  5  1 17  5]
 [18  4  3  8  3]
 [16 17  8 10  4]]


In [80]:
print(arr)
np.unique(arr,return_index=True,return_counts=True)

[2 4 3 1 4 1 8 1 7 3 2 4 5 2 1 3 2 5 7 1]


(array([1, 2, 3, 4, 5, 7, 8]),
 array([ 3,  0,  2,  1, 12,  8,  6], dtype=int32),
 array([5, 4, 3, 3, 2, 2, 1]))